/* Jonathan Therrien, Marieville, Québec. */
#include "tebdlc_core.h"
#include <assert.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

static tebdlc_fractional_gain gain(uint64_t n,uint64_t d,const char *ctx,const char *p1,const char *p2){ tebdlc_fractional_gain g={.numerator=n,.denominator=d,.typing={.domain="integrity",.dimension="coverage",.unit="ratio",.reference="R8-c-mirror",.context=ctx,.provenance={.count=0}}}; if(p1) g.typing.provenance.items[g.typing.provenance.count++]=p1; if(p2) g.typing.provenance.items[g.typing.provenance.count++]=p2; return g; }
static void test_basic_and_provenance(void){ tebdlc_fractional_gain a=gain(3,10,"proof-context","A","shared"),b=gain(2,5,"proof-context","B","shared"); tebdlc_fractional_result r=tebdlc_fractional_multiply(&a,&b); assert(r.status==TEBDLC_OK); assert(r.value.numerator==3U&&r.value.denominator==25U); assert(r.value.typing.provenance.count==3U); assert(strcmp(r.value.typing.provenance.items[0],"A")==0); assert(strcmp(r.value.typing.provenance.items[1],"B")==0); assert(strcmp(r.value.typing.provenance.items[2],"shared")==0); }
static void test_forbidden_ops(void){ assert(tebdlc_fractional_add_forbidden()==TEBDLC_FORBIDDEN_OPERATION); assert(tebdlc_fractional_sub_forbidden()==TEBDLC_FORBIDDEN_OPERATION); assert(tebdlc_fractional_div_forbidden()==TEBDLC_FORBIDDEN_OPERATION); }
static void test_context_boundary(void){ tebdlc_fractional_gain a=gain(3,10,"A",NULL,NULL),b=gain(3,10,"B",NULL,NULL); assert(tebdlc_fractional_multiply(&a,&b).status==TEBDLC_INCOMPATIBLE_CONTEXT); }
static void test_invalid_zero_and_unit(void){ tebdlc_fractional_gain z=gain(0,361,"proof-context",NULL,NULL),u=gain(361,361,"proof-context",NULL,NULL); assert(tebdlc_fractional_validate(&z)==TEBDLC_INVALID_REPRESENTATION); assert(tebdlc_fractional_validate(&u)==TEBDLC_INVALID_REPRESENTATION); }
static void test_cross_reduction(void){ tebdlc_fractional_gain a=gain(UINT64_MAX-1U,UINT64_MAX,"proof-context",NULL,NULL),b=gain(1U,UINT64_MAX-1U,"proof-context",NULL,NULL); tebdlc_fractional_result r=tebdlc_fractional_multiply(&a,&b); assert(r.status==TEBDLC_OK&&r.value.numerator==1U&&r.value.denominator==UINT64_MAX); }
static void test_capacity(void){ const uint64_t n=UINT64_C(4294967295),d=UINT64_C(4294967297); tebdlc_fractional_gain a=gain(n,d,"proof-context","A",NULL),b=gain(n,d,"proof-context","B",NULL); tebdlc_fractional_result r=tebdlc_fractional_multiply(&a,&b); assert(r.status==TEBDLC_CAPACITY_EXPANSION_REQUIRED); assert(r.left.numerator==n&&r.left.denominator==d&&r.right.numerator==n&&r.right.denominator==d); printf("capacity status=%d required_num_bits=%llu required_den_bits=%llu\n",(int)r.status,(unsigned long long)r.required_num_bits,(unsigned long long)r.required_den_bits); }
static void test_exhaustive_small_space(void){ unsigned long long count=0; for(uint64_t da=2;da<=40;da++) for(uint64_t na=1;na<da;na++) for(uint64_t db=2;db<=40;db++) for(uint64_t nb=1;nb<db;nb++){ tebdlc_fractional_gain a=gain(na,da,"proof-context",NULL,NULL),b=gain(nb,db,"proof-context",NULL,NULL); tebdlc_fractional_result r=tebdlc_fractional_multiply(&a,&b); assert(r.status==TEBDLC_OK); assert(r.value.numerator>0U&&r.value.numerator<r.value.denominator); count++; } assert(count==608400ULL); printf("exhaustive_pairs=%llu\n",count); }
int main(void){ test_basic_and_provenance(); test_forbidden_ops(); test_context_boundary(); test_invalid_zero_and_unit(); test_cross_reduction(); test_capacity(); test_exhaustive_small_space(); puts("TEBDLC C mirror tests: PASS"); return 0; }
