/* Jonathan Therrien, Marieville, Québec. */
#include "tebdlc_impotent.h"
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
static void make_big(tebdlc_poly_big_gain *g,unsigned long n,unsigned long d,const char *ctx,uint64_t node){ tebdlc_poly_big_init(g); mpz_set_ui(g->numerator,n); mpz_set_ui(g->denominator,d); g->node_id=node; g->typing.domain="integrity";g->typing.dimension="coverage";g->typing.unit="ratio";g->typing.reference="IMP-ref";g->typing.context=ctx; }
static void assess_pair(unsigned long a,unsigned long b,unsigned long d,tebdlc_imp_mass_relation expected){ tebdlc_poly_big_gain g1,g2;make_big(&g1,a,d,"C",1);make_big(&g2,b,d,"C",2);tebdlc_imp_set s={.members={&g1,&g2},.count=2,.integration_model="U1-model",.target_unit="U1"};tebdlc_imp_assessment out;tebdlc_imp_assessment_init(&out);assert(tebdlc_imp_describe_mass(&s,&out)==TEBDLC_IMP_OK);assert(out.relation_to_one==expected);assert(out.unitary_attained==0);char *mass=mpq_get_str(NULL,10,out.mass);printf("mass=%s relation=%d unitary=%d\n",mass,(int)out.relation_to_one,out.unitary_attained);free(mass);tebdlc_imp_assessment_clear(&out);tebdlc_poly_big_clear(&g1);tebdlc_poly_big_clear(&g2); }
static void test_three_regimes(void){assess_pair(100,100,361,TEBDLC_IMP_MASS_LT_ONE);assess_pair(180,181,361,TEBDLC_IMP_MASS_EQ_ONE);assess_pair(300,300,361,TEBDLC_IMP_MASS_GT_ONE);}
static void test_proof_gate(void){tebdlc_poly_big_gain a,b;make_big(&a,300,361,"C",1);make_big(&b,300,361,"C",2);tebdlc_imp_set s={.members={&a,&b},.count=2,.integration_model="U1-model",.target_unit="46"};tebdlc_imp_assessment x;tebdlc_imp_assessment_init(&x);assert(tebdlc_imp_describe_mass(&s,&x)==TEBDLC_IMP_OK);assert(mpq_cmp_ui(x.mass,1,1)>0&&x.unitary_attained==0);assert(tebdlc_imp_apply_integrability_proof(&x,1,1,1,0)==TEBDLC_IMP_PROOF_REQUIRED&&x.unitary_attained==0);assert(tebdlc_imp_apply_integrability_proof(&x,1,1,1,1)==TEBDLC_IMP_OK&&x.unitary_attained==1);tebdlc_imp_assessment_clear(&x);tebdlc_poly_big_clear(&a);tebdlc_poly_big_clear(&b);}
static void test_large_reference(void){tebdlc_poly_big_gain a,b;make_big(&a,999999UL,1000003UL,"C",7);make_big(&b,999999UL,1000003UL,"C",8);tebdlc_imp_set s={.members={&a,&b},.count=2,.integration_model="wide",.target_unit="U-wide"};tebdlc_imp_assessment x;tebdlc_imp_assessment_init(&x);assert(tebdlc_imp_describe_mass(&s,&x)==TEBDLC_IMP_OK);assert(mpq_cmp_ui(x.mass,1,1)>0&&x.unitary_attained==0);tebdlc_imp_assessment_clear(&x);tebdlc_poly_big_clear(&a);tebdlc_poly_big_clear(&b);}
static void test_context_reject(void){tebdlc_poly_big_gain a,b;make_big(&a,100,361,"A",1);make_big(&b,100,361,"B",2);tebdlc_imp_set s={.members={&a,&b},.count=2,.integration_model="U",.target_unit="U"};tebdlc_imp_assessment x;tebdlc_imp_assessment_init(&x);assert(tebdlc_imp_describe_mass(&s,&x)==TEBDLC_IMP_INCOMPATIBLE_REFERENCE);tebdlc_imp_assessment_clear(&x);tebdlc_poly_big_clear(&a);tebdlc_poly_big_clear(&b);}
int main(void){test_three_regimes();test_proof_gate();test_large_reference();test_context_reject();puts("TEBDLC impotent gain tests: PASS");return 0;}
