/* Jonathan Therrien, Marieville, Québec. */
#include "tebdlc_stagnation.h"
#include <openssl/evp.h>
#include <stdlib.h>
#include <string.h>
#include <zlib.h>
typedef struct { unsigned char *p; size_t len,cap; } buf;
static int grow(buf *b,size_t add){ if(add>SIZE_MAX-b->len)return 0; size_t need=b->len+add;if(need<=b->cap)return 1;size_t nc=b->cap?b->cap:256;while(nc<need){if(nc>SIZE_MAX/2)return 0;nc*=2;}void *q=realloc(b->p,nc);if(!q)return 0;b->p=q;b->cap=nc;return 1; }
static int put(buf *b,const void *p,size_t n){if(!grow(b,n))return 0;memcpy(b->p+b->len,p,n);b->len+=n;return 1;}
static int put_u64(buf *b,uint64_t v){unsigned char x[8];for(int i=7;i>=0;--i){x[i]=(unsigned char)(v&0xffU);v>>=8U;}return put(b,x,8);}
static int put_str(buf *b,const char *s){size_t n=s?strlen(s):0;if(n>UINT64_MAX)return 0;return put_u64(b,(uint64_t)n)&&put(b,s,n);}
static int hash256(const unsigned char *p,size_t n,unsigned char out[32]){EVP_MD_CTX *c=EVP_MD_CTX_new();if(!c)return 0;unsigned int l=0;int ok=EVP_DigestInit_ex(c,EVP_sha256(),NULL)==1&&EVP_DigestUpdate(c,p,n)==1&&EVP_DigestFinal_ex(c,out,&l)==1&&l==32;EVP_MD_CTX_free(c);return ok;}
static char *dupstr(const char *s){if(!s)return NULL;size_t n=strlen(s)+1;char *p=malloc(n);if(p)memcpy(p,s,n);return p;}
void tebdlc_st_archive_init(tebdlc_st_archive *a){if(a)memset(a,0,sizeof(*a));}
void tebdlc_st_archive_clear(tebdlc_st_archive *a){if(!a)return;free(a->canonical);free(a->compressed);free(a->origin_context);free(a->call_context);memset(a,0,sizeof(*a));}
static tebdlc_st_status serialize_gain(const tebdlc_poly_big_gain *g,unsigned char **out,size_t *len){if(tebdlc_poly_big_validate(g)!=TEBDLC_POLY_OK)return TEBDLC_ST_INVALID;buf b={0};char *n=mpz_get_str(NULL,10,g->numerator),*d=mpz_get_str(NULL,10,g->denominator);if(!n||!d){free(n);free(d);return TEBDLC_ST_ALLOC;}int ok=put(&b,"TST1",4)&&put_str(&b,n)&&put_str(&b,d)&&put_str(&b,g->typing.domain)&&put_str(&b,g->typing.dimension)&&put_str(&b,g->typing.unit)&&put_str(&b,g->typing.reference)&&put_str(&b,g->typing.context)&&put_u64(&b,(uint64_t)g->typing.provenance.count);for(size_t i=0;ok&&i<g->typing.provenance.count;++i)ok=put_str(&b,g->typing.provenance.items[i]);ok=ok&&put_u64(&b,(uint64_t)g->genealogy.count);for(size_t i=0;ok&&i<g->genealogy.count;++i)ok=put_u64(&b,g->genealogy.node_ids[i]);ok=ok&&put_u64(&b,g->node_id);free(n);free(d);if(!ok){free(b.p);return TEBDLC_ST_ALLOC;}*out=b.p;*len=b.len;return TEBDLC_ST_OK;}
tebdlc_st_status tebdlc_st_stagnate_gain(const tebdlc_poly_big_gain *gain,tebdlc_st_archive *out){if(!out)return TEBDLC_ST_INVALID;tebdlc_st_archive_clear(out);tebdlc_st_status s=serialize_gain(gain,&out->canonical,&out->canonical_len);if(s!=TEBDLC_ST_OK)return s;if(!hash256(out->canonical,out->canonical_len,out->sha256)){tebdlc_st_archive_clear(out);return TEBDLC_ST_INVALID;}out->origin_context=dupstr(gain->typing.context);if(!out->origin_context){tebdlc_st_archive_clear(out);return TEBDLC_ST_ALLOC;}out->state=TEBDLC_ST_STAGNATED;return TEBDLC_ST_OK;}
tebdlc_st_status tebdlc_st_compress(tebdlc_st_archive *a){if(!a||a->state!=TEBDLC_ST_STAGNATED||!a->canonical)return TEBDLC_ST_INVALID;uLongf cap=compressBound((uLong)a->canonical_len);unsigned char *p=malloc((size_t)cap);if(!p)return TEBDLC_ST_ALLOC;int z=compress2(p,&cap,a->canonical,(uLong)a->canonical_len,Z_BEST_COMPRESSION);if(z!=Z_OK){free(p);return TEBDLC_ST_COMPRESS_FAIL;}free(a->compressed);a->compressed=p;a->compressed_len=(size_t)cap;a->state=TEBDLC_ST_COMPRESSED;return TEBDLC_ST_OK;}
tebdlc_st_status tebdlc_st_decompress_verify(tebdlc_st_archive *a){if(!a||!a->compressed||a->compressed_len==0||a->canonical_len==0)return TEBDLC_ST_INVALID;unsigned char *p=malloc(a->canonical_len);if(!p)return TEBDLC_ST_ALLOC;uLongf n=(uLongf)a->canonical_len;int z=uncompress(p,&n,a->compressed,(uLong)a->compressed_len);if(z!=Z_OK||n!=a->canonical_len){free(p);return TEBDLC_ST_DECOMPRESS_FAIL;}unsigned char h[32];if(!hash256(p,(size_t)n,h)||memcmp(h,a->sha256,32)!=0||memcmp(p,a->canonical,a->canonical_len)!=0){free(p);return TEBDLC_ST_INTEGRITY_FAIL;}free(p);return TEBDLC_ST_OK;}
tebdlc_st_status tebdlc_st_reactivate(tebdlc_st_archive *a,const char *call_context){if(!a||a->state!=TEBDLC_ST_COMPRESSED||!call_context)return TEBDLC_ST_INVALID;tebdlc_st_status s=tebdlc_st_decompress_verify(a);if(s!=TEBDLC_ST_OK)return s;char *c=dupstr(call_context);if(!c)return TEBDLC_ST_ALLOC;free(a->call_context);a->call_context=c;a->state=TEBDLC_ST_REACTIVATED;return TEBDLC_ST_REVALIDATION_REQUIRED;}
tebdlc_st_status tebdlc_st_revalidate(tebdlc_st_archive *a,int proof_valid,int *became_active){if(!a||a->state!=TEBDLC_ST_REACTIVATED)return TEBDLC_ST_INVALID;if(became_active)*became_active=0;if(!proof_valid){a->state=TEBDLC_ST_STAGNATED;return TEBDLC_ST_REVALIDATION_REQUIRED;}a->state=TEBDLC_ST_REVALIDATED;if(became_active)*became_active=1;return TEBDLC_ST_OK;}
