/* Jonathan Therrien, Marieville, Québec. */
#include "tebdlc_stagnation.h"
#include <assert.h>
#include <stdio.h>
#include <string.h>
static void gain(tebdlc_poly_big_gain *g){tebdlc_poly_big_init(g);mpz_ui_pow_ui(g->numerator,3,100);mpz_ui_pow_ui(g->denominator,10,100);g->typing.domain="integrity";g->typing.dimension="coverage";g->typing.unit="ratio";g->typing.reference="ST-ref";g->typing.context="C-origin";g->typing.provenance.items[0]="source-A";g->typing.provenance.items[1]="source-B";g->typing.provenance.count=2;g->genealogy.node_ids[0]=1;g->genealogy.node_ids[1]=2;g->genealogy.node_ids[2]=100;g->genealogy.count=3;g->node_id=100;}
static void test_roundtrip_and_context(void){tebdlc_poly_big_gain g;gain(&g);tebdlc_st_archive a;tebdlc_st_archive_init(&a);assert(tebdlc_st_stagnate_gain(&g,&a)==TEBDLC_ST_OK);assert(a.state==TEBDLC_ST_STAGNATED);assert(strcmp(a.origin_context,"C-origin")==0);assert(tebdlc_st_compress(&a)==TEBDLC_ST_OK);assert(a.state==TEBDLC_ST_COMPRESSED);assert(tebdlc_st_decompress_verify(&a)==TEBDLC_ST_OK);printf("canonical=%zu compressed=%zu\n",a.canonical_len,a.compressed_len);assert(tebdlc_st_reactivate(&a,"C-call-new")==TEBDLC_ST_REVALIDATION_REQUIRED);assert(a.state==TEBDLC_ST_REACTIVATED);assert(strcmp(a.origin_context,"C-origin")==0);assert(strcmp(a.call_context,"C-call-new")==0);int active=0;assert(tebdlc_st_revalidate(&a,0,&active)==TEBDLC_ST_REVALIDATION_REQUIRED);assert(active==0&&a.state==TEBDLC_ST_STAGNATED);assert(strcmp(a.origin_context,"C-origin")==0);tebdlc_st_archive_clear(&a);tebdlc_poly_big_clear(&g);}
static void test_valid_revalidation(void){tebdlc_poly_big_gain g;gain(&g);tebdlc_st_archive a;tebdlc_st_archive_init(&a);assert(tebdlc_st_stagnate_gain(&g,&a)==TEBDLC_ST_OK);assert(tebdlc_st_compress(&a)==TEBDLC_ST_OK);assert(tebdlc_st_reactivate(&a,"C-call-validated")==TEBDLC_ST_REVALIDATION_REQUIRED);int active=0;assert(tebdlc_st_revalidate(&a,1,&active)==TEBDLC_ST_OK);assert(active==1&&a.state==TEBDLC_ST_REVALIDATED);assert(strcmp(a.origin_context,"C-origin")==0);tebdlc_st_archive_clear(&a);tebdlc_poly_big_clear(&g);}
static void test_corruption_detected(void){tebdlc_poly_big_gain g;gain(&g);tebdlc_st_archive a;tebdlc_st_archive_init(&a);assert(tebdlc_st_stagnate_gain(&g,&a)==TEBDLC_ST_OK);assert(tebdlc_st_compress(&a)==TEBDLC_ST_OK);assert(a.compressed_len>4);a.compressed[a.compressed_len/2]^=0x5aU;tebdlc_st_status s=tebdlc_st_decompress_verify(&a);assert(s==TEBDLC_ST_DECOMPRESS_FAIL||s==TEBDLC_ST_INTEGRITY_FAIL);tebdlc_st_archive_clear(&a);tebdlc_poly_big_clear(&g);}
int main(void){test_roundtrip_and_context();test_valid_revalidation();test_corruption_detected();puts("TEBDLC stagnation chain tests: PASS");return 0;}
